#!/bin/bash
set -e # exit on exception

# Set Variables
app_port=`config-get port`
app_url=`config-get url`

juju-log "Downloading dependencies from apt"

# Grab Node.js and NPM as well as build-essential for a few node modules
apt-get install -y  build-essential
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
apt-get install -y nodejs

juju-log "Setting Node.js Version to 4.5"


juju-log "Downloading Rocket.Chat"

# Download latest stable version of Rocket.Chat
curl -L  https://download.rocket.chat/stable  -o rocket.chat.tgz

juju-log "Installing Rocket.Chat"

# Extract
tar zxvf rocket.chat.tgz

# Move the bundle to the desired location
mv bundle /opt/rocket.chat

cd /opt/rocket.chat/programs/server

juju-log "Installing Node Modules from NPM"

# Install Node.js Dependencies
npm install 

cd ../..

# Creating Config file
cat > /opt/rocket.chat/rocketchat.config <<EOS
export PORT=${app_port}
export ROOT_URL=${app_url}
EOS

juju-log "Creating service file"

cat > /etc/init/rocketchat.conf <<EOS
description "Rocket.Chat server"

start on (net-device-up
          and local-filesystems
          and runlevel [2345])
stop on runlevel [!2345]

respawn

script
  cd /opt/rocket.chat
  . /opt/rocket.chat/rocketchat.config
  /usr/bin/node main.js
end script
EOS

open-port $app_port

juju-log "Finished Installation"
